haproxy_ca_url: "https://pki.guerande.local.net:9000"
haproxy_cert_dir: "/etc/haproxy/certs"
haproxy_cert_name: "wildcard.guerande.local.net"
haproxy_cert_path: "{{ haproxy_cert_dir }}/{{ haproxy_cert_name }}.pem"
haproxy_step_ca_path: "/etc/step-ca"
