machikiflix_traefik_folder: /opt/traefik/
machikiflix_servarr_folder: /opt/servarr/
machikiflix_torrent_folder: /opt/torrent/
machikiflix_arr_folder: /opt/arr
machikiflix_gluetun_folder: /opt/gluetun
machikiflix_data: /data/tvshows
