$ANSIBLE_VAULT;1.2;AES256;machikiflix
39313465623437306364663331653434643637633433326539393061376339383362623163373838
3766366131653462663130613336346561343162313333360a393536313265333632666238653162
65633033383035616661303331383933373331303937343563306436623166366631626537353765
3166623635663734610a353436626639643532636231356239623437316534333430363566373565
61313466316431373438333238323762326337326330376432373963633462376662376136363731
30366636336533353836383563373533303535346633326531323936363361616535376562663634
36666531616562623461613266643836393830323832376535383733376133363230323033363938
31313831643265623531363138316336663339323164396634343136383835363163323061326237
30653839646130316437656165336333323962303333643833376333313363653236653136353738
35306530313066646638643863396233653863613336653565383830396361636634346464373864
34393837353265653861636665383566663961356465303030386661346537373435303635323465
62383065623431396630666163343232326463663131613430633233313439303930383235663434
33623932643132373137636335343032303034663533366630336332373139623462666430663231
38353133383138633163666437633630386136306636343166373732653435626166313330333439
326638383061623437373265623135636461
