services:
  traefik:
    image: "traefik:v3.4"
    container_name: "traefik"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/opt/traefik/traefik.yml:/etc/traefik/traefik.yml"

  whoami:
    image: traefik/whoami
    container_name: "whoami"
    restart: unless-stopped
    networks:
      - proxy
    command:
       # It tells whoami to start listening on 2001 instead of 80
       - --port=2001
       - --name=whoami
    labels:
      traefik.enable: "true"
      traefik.http.routers.whoami.service: whoami
      traefik.http.routers.whoami.rule: Host('machikiflix.guerande.local.net') && PathPrefix(`/whoami`)
      traefik.http.services.whoami.loadbalancer.server.port: 2001
      traefik.http.routers.whoami.entrypoints: "web"

networks:
  proxy:
    name: proxy